# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0fadd7c1ab707581abf0716f10629f7ff7132e178277424fa952b65c51aa1beef1b6c2dc5c3a5cd54bccdb48b199ce294bedddddd6288ea0544373193ed982ac

test:
  secret_key_base: bedf211e2f626eda4f03860f79fefc002ca0962ad34be93a9d873c64549f374bbece71f39dcd949941d89c1ff0e2ffaf0532c732b2d361f256d4e577d4da32fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
